version: '3.8'

services:
  # --- INFRASTRUCTURE ---
  eureka-service:
    image: ndourbamba18/eureka-service:latest
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  config-service:
    image: ndourbamba18/config-service:latest
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - microservices-net

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - microservices-net

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - microservices-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - microservices-net

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    networks:
      - microservices-net

  # --- MICROSERVICES ---
  gateway-service:
    image: ndourbamba18/gateway-service:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - config-service
      - eureka-service
    networks:
      - microservices-net

  product-service:
    image: ndourbamba18/product-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - config-service
      - eureka-service
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge